name: my_messenger_app
description: "A secure MTProto messenger"
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_v2ray: ^1.2.0
flutter:
  uses-material-design: true
